name: Release Pipeline

on:
  push: {}

jobs:
  release-pipeline:
    name: Release Pipeline\
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@u4

      - name: Setup Dotnet tools
        uses: actions/setup-dotnet@u4
        with:
          dotnet-version: '8.0.x'

      - name: Run Core Test
        run: dotnet test .\src\DevOpsDaysTasks.Core.Tests

      - name: "hello Pipeline"
        run: echo "hello Pipeline"
